language: scala
scala:
- 2.11.12
- 2.12.6
jdk:
- oraclejdk8
script:
- sbt coverage test coverageReport
deploy:
  skip_cleanup: true
  provider: script
  script: "./.travis/deploy.sh $TRAVIS_TAG"
  on:
    condition: '"${TRAVIS_SCALA_VERSION}" == "2.12.6"'
    tags: true
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
  - BINTRAY_SNOWPLOW_MAVEN_USER=
  - BINTRAY_SNOWPLOW_MAVEN_API_KEY=
  - SONA_USER=snowplow
  - SONA_PASS=
  - secure: 7M48lkBfeKFectdFiDLIbRr0wwez7gxOnvqiAnsmHQ5U1HuJd0nPnwXMkycMZs9/UK3ce7dPfrr2tDjF/PbBGOumq4Tsmoog8wwV1E0gwNJEOLQiUCkY5oq1V33tBfqyWf+kDP9JHoyUZoF0jT2EiO72EO0XBxHza51ch2vBC0LRIPihErzBXODo+rVa9/FFtWpbraPHVdRCuyh40+rId1XPI14bJN2zI2VJ+BqUD9a6KCnjPK43R7smvjXQyz7HBFjRcO7493LDMtZcnT9yomRKtNdF9tE8WWfQ7XVVSIsD8gnCzsIUwIyMy5TbrgLISm255EXtd38KgD3SrTLs+vJEkvRI4eQ5QFmsY8j75t0Z9CNhJNjl+UKaj+poheDYnWaudHtJsBqTmil2d5z2TTLlZvPa0IUmt+Yl5mQgEZFMxb6zGGnkixCPoHs13cDyHViYAEQ1QL0GYr3HjHlk+JqxdSyUMilbQCLnIgEK/pdCTl5pWYQn90qvO+op8rE8pSO27GXvCVjTM323BcL6h0Ge/+zGrrSpzREV8t9xCs1UoiDlGViQkUuqH90fpaQjK6AIklqQfZtDogmj8nRoPxwqzNBAB5cp3D0U5ekvGPK4byLx4tdenfacceJ4fj00TIgALrL/YOEJRaUF0Af03CtAxjF8KsEtMke0L368Na0=
  - secure: OXRSiJG88IbU3hEpEdF990isGzaZZIqi9l9NxSScnAMXQnRi/mUVrGb6XYzoA1Z8e+4XtK/0aiWxqCpXsDT6haQZSGwqUkjR/dHM3T7KtDrhvvoC6V8MoWHMT3WJplscrRkcNExqdt9k3xioYgsx7f0/LVS13I5a2vXjJ171ltTCFcmlDW5B2oUo268GJKwzsolobAWuJGFoj9Qwq/B3mCqwn7illLTPzDmprWsymFXiBYRm9/hzE5ITs6djLU+g6IsfFmN6hdSovRk4lfmGQThhvEV+PrY38PlU2iXoLzkF5fjitxA2Lx8UH0M6kwA8Hvbuf6mDECCQ4WQWjdY/1htF8gMWwh7N0z9DaWmCU0upqnIAKUSKwswVLcA6CmEHCTY5emFwtHYIom5aEQZYa6FYUyg4s1et7wv7xwpK99afCNy2eKrVAq0AhN+T7bd9UQchbYgKXDzZrC8Ua4sfIT9FOwZCCyTcF1kQGgDKzJ/vtD8gwlH5Mb1jV0sHJSlucL9vCrbUO/q2GZCw0GDcBBLYj0Dl9entnBdNAuJlp2xVyOHe4ZNC7+xQPAXnpTkJicv5zscXX8vxkHI9peMIrlFtdk1O6ej+5nZwSWLPY0qBy/X92iPV5KHONgJOO7k+SaQbKDQs5sWL4f1e+eYcgUpEXCWNiHiER+ajXWnD5iM=
